### ISSUE TITLE
mphf_benchmark fork

### ISSUE THREAD

**Issue by beling** [roberto-trani/mphf_benchmark#1]
Hello,

I'm Piotr Beling, PhD from University of Łódź.
For my own research, I began to develop a fork of mphf_benchmark available at:
https://github.com/beling/mphf_benchmark

In my fork I:
- I've added xor-shifts 32 and 64 generators for keys,
- I've updated PTHash to the newest version and added its support for its partitioned variant,
- some methods (especially PTHash) are run also with multiple threads,
- only one variant of the method can be run with new variant flag,
- I fixed the bug that cause coping all the keys.

Please feel free to copy some or all my changes to your branch. I especially recommended the following one that fixes the bug with keys duplication:
https://github.com/beling/mphf_benchmark/commit/953a44c085c4790a63fea8348c72f9e60e5224be

Best regards
Piotr Beling

**Comment by jermp** [comment]
Hi Piotr and thank you for your interest. You're very welcome to work on the benchmark and submit pull requests. Would you? I think it is the fastest way of incorporating the changes. Thanks!
Are you also considering to add other methods?

Best,
-Giulio

**Comment by beling** [comment]
Hi Giulio,
I've just opened pull-request with my changes.

I am not considering to add new methods, as I develop my methods in Rust, here:
https://github.com/beling/bsuccinct-rs
My methods have no C/C++ API, so I have to develop another mphf_benchamrk in Rust. It can run methods implemented in Rust: my methods and boomphf. All are variants of fingerprinting-based minimal perfect hashing (BBHash). However, my methods significantly improve BBHash, reducing the size even to about 2.1 bits / key (at the cost of slower construction speed).
I hope to publish the paper about my method (the publication is in major revision state).

Best,
Piotr

PS. Are you open to scientific collaboration on MPHFs? At my University, I am the only person working on this topic, so unfortunately I have to work alone.

**Comment by jermp** [comment]
Thanks Piotr for your changes; I've merged the pull request.

I have only some minor reservations on the use of `variant`, here:
https://github.com/roberto-trani/mphf_benchmark/blob/main/src/mphf_benchmark.cpp#L102
and here https://github.com/roberto-trani/mphf_benchmark/blob/main/src/mphf_benchmark.cpp#L144,
shouldn't they be just 1, 2, 3, etc.?

> I am not considering to add new methods, as I develop my methods in Rust, here:
> https://github.com/beling/bsuccinct-rs
> My methods have no C/C++ API, so I have to develop another mphf_benchamrk in Rust. It can run methods implemented in Rust: my methods and boomphf. All are variants of fingerprinting-based minimal perfect hashing (BBHash). However, my methods significantly improve BBHash, reducing the size even to about 2.1 bits / key (at the cost of slower construction speed).
> I hope to publish the paper about my method (the publication is in major revision state).

That's great and I'm looking forward to know more about your method!
Would you consider porting it to C++? That's might be the best option to incorporate it into this framwork.
Anyway, for comparisons, I think it is perfectly fine to compare a C++ implementation with a Rust one.

> PS. Are you open to scientific collaboration on MPHFs? At my University, I am the only person working on this topic, so unfortunately I have to work alone.

Absolutely yes! Just let me know if you want to discuss something (giulioermanno.pibiri@unive.it).

**Comment by beling** [comment]
> Thanks Piotr for your changes; I've merged the pull request.

Thank you!

> I have only some minor reservations on the use of `variant`, here: https://github.com/roberto-trani/mphf_benchmark/blob/main/src/mphf_benchmark.cpp#L102 and here https://github.com/roberto-trani/mphf_benchmark/blob/main/src/mphf_benchmark.cpp#L144, shouldn't they be just 1, 2, 3, etc.?

I also have doubts here, and I really don't know which solution is better. Of course, variants other than 1, 2, 3, .... refer to the parameters of the methods. Please let me know if in your opinion 1, 2, 3, ... is better. then I will change to make it so.

> Would you consider porting it to C++?

No. But I am considering adding C API to them, to enable calling from any language.

> That's might be the best option to incorporate it into this framework. Anyway, for comparisons, I think it is perfectly fine to compare a C++ implementation with a Rust one.

I agree. The compilers are able to make similar optimizations.

> That's great and I'm looking forward to know more about your method! 
> (...)
> Just let me know if you want to discuss something ([giulioermanno.pibiri@unive.it](mailto:giulioermanno.pibiri@unive.it)).

Soon (probably in a few days) I will send an email on these topics.

**Comment by jermp** [comment]
> I also have doubts here, and I really don't know which solution is better. Of course, variants other than 1, 2, 3, .... refer to the parameters of the methods. Please let me know if in your opinion 1, 2, 3, ... is better. then I will change to make it so.

Since any other choice than "1, 2, 3, ..." does not necessarily have a better meaning, I would default to "1, 2, 3, ...".
Another option is to include cmd arguments for all methods. For example: `--fch [c]` or `--chd [lambda]` or `--pthash [c] [alpha]`, etc.

> No. But I am considering adding C API to them, to enable calling from any language.

Ok, it was just a curiosity. I would like to port PTHash and some other libraries to Rust but I have to learn the language first!

> Soon (probably in a few days) I will send an email on these topics.

Great! You're very welcome.

**Comment by beling** [comment]
> Since any other choice than "1, 2, 3, ..." does not necessarily have a better meaning, I would default to "1, 2, 3, ...". Another option is to include cmd arguments for all methods. For example: `--fch [c]` or `--chd [lambda]` or `--pthash [c] [alpha]`, etc.

good idea, but requires some work; I think that the variants are OK for now

> Ok, it was just a curiosity. I would like to port PTHash and some other libraries to Rust but I have to learn the language first!

Rust is worth learning. Since I switched from C++ to Rust, my efficiency has greatly increased because I don't have to watch out for 99% of the errors I had to in C++.

This is a perfect example of a bug impossible to make in Rust:
https://github.com/beling/mphf_benchmark/commit/953a44c085c4790a63fea8348c72f9e60e5224be
Rust just move by default. If I need to clone the vector, I have to call clone() method, and so I can easy see where I use a lot of memory. Moreover, using variable after move is a COMPILE error in Rust, so move by default cannot surprise me.

If you decide to rewrite PTHash to Rust then I will help you.


I just opened new pull-request. It is important for me as I examine (using memusage memory profiler) how much (peak) memory the methods use during construction and I need method of reading input from stdin that not too much memory. And this is easy possible only when the number of strings is known in advance and reserve() can be called.
For example reading uk-2005 database without pre-reserving memory in vector takes 20% more memory than necessary.

BTW. I found that PTHash needs about 25-30 bytes / key during building, excluding the memory occupied by the keys themselves. I'm wondering if you expected such amount?

**Comment by jermp** [comment]
> If you decide to rewrite PTHash to Rust then I will help you.

Thank you! I have to reserve some time to learn Rust.

> BTW. I found that PTHash needs about 25-30 bytes / key during building, excluding the memory occupied by the keys themselves. I'm wondering if you expected such amount?

What construction modality are you using? Internal memory or external memory? If you take the max rss with `/urs/bin/time`, you will get misleading numbers in external memory. See this conversation here: https://github.com/jermp/sshash/issues/10. Anyway, 25-30 bytes seem too much... Can you tell me what experiments you're running?

**Comment by beling** [comment]
> What construction modality are you using? Internal memory or external memory? If you take the max rss with `/urs/bin/time`, you will get misleading numbers in external memory. See this conversation here: [jermp/sshash#10](https://github.com/jermp/sshash/issues/10). Anyway, 25-30 bytes seem too much... Can you tell me what experiments you're running?

I just run pthash with mphf_benchmark (for example variant 1) with some keys generated by xs64. I use -n 39459925 (this is the size of uk2005) but other amounts should give the same results.

Then I run mphf_benchmark with the same keys, but using non-existed variant (for example --variant 9) to see how much memory are used by the keys itself (this is almost exactly 64bit/key).

And I obtain peak heap memory as a difference from the first and second run.

I use this to measure the usage of memory:
https://man7.org/linux/man-pages/man1/memusage.1.html

**Comment by beling** [comment]
`memusage ./mphf_benchmark pthash --variant 1 --gen xs64 -n 39459925`
gives me `heap peak: 1309230542`
`memusage ./mphf_benchmark pthash --variant 9 --gen xs64 -n 39459925`
gives me `heap peak: 315757086`

(1309230542−315757086)÷39459925=25,176770001

**Comment by beling** [comment]
How much memory should pthash use during build?

**Comment by jermp** [comment]
Ok so you're running in internal memory. The cost is dominated by the size of the hashcodes, so it should take `[bytes-for-keys]` + `[n * 8 bytes]` (8-byte hashes) + some overhead due to temporary structures but it should be small.
What is the RAM used looking at top or htop? That's how we measured the RAM at building time.

**Comment by beling** [comment]
I've tried few methods with similar results, for example:
https://man7.org/linux/man-pages/man1/time.1.html with "%P"
I think GNU Time measure process time with the same method as top/htop.
I don't know how to see result in `top` when the process ends quite quickly.

**Comment by jermp** [comment]
Using htop, I see `./mphf_benchmark pthash --variant 1 --gen xs64 -n 39459925` uses 0.8 GB, so 20.3 bytes per key.

**Comment by jermp** [comment]
We can use this method to calculate an estimate: https://github.com/jermp/pthash/blob/master/include/builders/internal_memory_builder_single_phf.hpp#L161

**Comment by beling** [comment]
I just checked:
`/usr/bin/time -f "%M" ./mphf_benchmark pthash --variant 1 --gen xs64 -n 39459925`
gives 1211812 kbytes, which is about 31,446980398 bytes / key.

I suppose that there is some issue in code that cause a peak that lasts a very short time (impossible to see in top/htop). I guess that some copying of data somewhere when changing the size of a vector, for example when pushing.
I do recommend heaptrack or Valgrind to found this.

**Comment by jermp** [comment]
I've made a quick commit to verify the estimation (~22.22 bytes/key).

    ./mphf_benchmark pthash --variant 1 --gen xs64 -n 39459925
    Generating 39459925 random keys by xs64 generator (the name of the generator contains the size of each key in bits).
    Algorithm PTHash(encoder=compact-compact, c=7, alpha=0.99, threads=1)
    Estimated num_bytes for construction: 876769476 (22.2192 bytes/key)
    Average Construction time: 13s 444ms (13.444s)
    Average Space usage: 3.25 bits/key
    Average Lookup time: 26.977ns

**Comment by beling** [comment]
You can run:
`valgrind --tool=massif ./mphf_benchmark pthash --variant 1 --gen xs64 -n 39459925`
which generate the file that you can watch in massif-visualizer to see where the memory used in peak was reserved

**Comment by beling** [comment]
Does this estimation exclude the memory occupied by the keys themselves?
If it does, then it is quite close to 25,176770001 bytes / key which I obtained from memusage.

**Comment by jermp** [comment]
> Does this estimation exclude the memory occupied by the keys themselves?
> If it does, then it is quite close to 25,176770001 bytes / key which I obtained from memusage.

Yes exactly.

I'm now installing the massif-visualizer. Thank you for the suggestion!

**Comment by beling** [comment]
Good luck!
I've also read that heaptrack (GUI also exists) is good tool. However, I have not too much experience with heaptrack.

**Comment by jermp** [comment]
Cannot install the massif-visualiser on mac...
I've found this online https://boutglay.com/massifjs/ but it's just a plot.
Anyway, from the massif file generated from valgrind I got a peak of 33.2 bytes/key but an average of 20.65 bytes/key.

**Comment by beling** [comment]
Unfortunately, this GUI in js shows virtually no details.
