### ISSUE TITLE
bbhash + strings = MPHF contains out of range values

### ISSUE THREAD

**Issue by beling** [roberto-trani/mphf_benchmark#5]
When I try to run bbhash with strings keys, then the program ends with `MPHF contains out of range values` exception.
bbhash works very well with integer keys.

Have you noticed this problem Giulio? Is it the fault of mphf_benchmark or bbhash?
I don't see anything suspicious in the mphf_benchmark code, while the bbhash code is a bit unreadable to me.

Example run:
`cat uk-2005-nat.urls | ./mphf_benchmark bbhash`

And output:
`4 threads available for multi-threaded calculations
Reading keys from stdin
Read 39459925 keys, with average length 71.37
Algorithm BBhash(gamma=1, num_threads=1)
Average Construction time: 57s 778ms (57.778s)
Average Space usage: 3.06 bits/key
terminate called after throwing an instance of 'std::runtime_error'
  what():  MPHF contains out of range values`

**Comment by jermp** [comment]
Hi Piotr,
mmh yeah that's suspicious and I'm told quite many people have problems with BBHash: I remember Roberto Trani had to look at this specific branch here https://github.com/rizkg/BBHash/tree/alltypes to make it work with strings.
Let me know if this can help!

**Comment by beling** [comment]
Thank you very much! Luckily, besides mine, there is one other implementation of this algorithm in Rust, so I don't have to compare the results with BBHash. I am closing Issue because the error is on BBHash's side.
