### ISSUE TITLE
Add another CHD implement 

### ISSUE THREAD

**Issue by PeterRK** [roberto-trani/mphf_benchmark#6]
Cmph is too old. Another CHD implement optimized for throughput: https://github.com/PeterRK/fastCHD

**Comment by roberto-trani** [comment]
Hi @PeterRK ,
Thank you for suggesting something to include in the benchmark.
Unfortunately, I could not find any comparison benchmark to say whether it is faster or more compact than CHD.

Do you have any benchmark of your implementation and CHD on the same data and same machine?
Is this implementation related to a research paper or similar?

**Comment by PeterRK** [comment]
That is an new implement of CHD algorithm with fixed param and parallel technique for industry, not a competitor. I think it is unfair to claim CHD algorithm slow by defeating an outdated implement in cmph.

**Comment by jermp** [comment]
Hello @PeterRK , that's what everybody in the research community identifies with the CHD algorithm.
Also, as far as we know, the cmph implementation is the one widely used in both academia **and** industry.
It is therefore good to benchmark against that library that everybody uses. (I 100% agree with you that it is out-dated by now.)

PTHash is similar in spirit to CHD, so even an optimized implementation of CHD is unlikely to beat PTHash or FCH for lookup speed. Ideally, one would need to re-implement all algorithms under the same framework.

**Comment by roberto-trani** [comment]
Hi @PeterRK  , before discussing any integration in our benchmark, we need some evidence that your implementation is competitive in construction speed, lookup speed, or space with respect to the cmph one (that is the official CHD implementation).

**Comment by PeterRK** [comment]
@jermp I didn’t aim to claim CHD can beat PTHash. But CHD deserves a better score.

**Comment by PeterRK** [comment]
<img width="880" alt="2023-05-12 224040" src="https://github.com/roberto-trani/mphf_benchmark/assets/4464013/d0e2c54f-e832-42f0-8e92-82147831cb18">
@roberto-trani There is 32B payload with 8B key in benchmark of fastCHD, because most jobs in real world need looking up data instead of an index. Filling & fetching data bings much overhead, but fastCHD is still fast enough.

**Comment by PeterRK** [comment]
Test above was run on EPYC-7K83 (Zen3) cloud node with hugepage.
CHD algorithm was underestimated. It can run even faster with some dedicated tuning, but I think that is unfair to the competitors.

**Comment by PeterRK** [comment]
> Cmph is too old. Another CHD implement optimized for throughput: https://github.com/PeterRK/fastCHD

I have modified this repo, changing the default algorithm to SHD. CHD can be found in chd branch.

**Comment by jermp** [comment]
Hi @PeterRK, it looks like your SHD is similar to PTHash in that it uses a skewed distribution of keys into buckets.
Would you plug your implementation in this benchmark so that we can have a fair comparison??

Thank you!

**Comment by jermp** [comment]
Closed for inactivity. Feel free to re-open it in case.
